project_id = "naoyxoaqbffdzbhkgbte"

[functions.notify-access-request]
verify_jwt = false

[functions.send-access-confirmation]
verify_jwt = false

[functions.receive-resend-webhook]
verify_jwt = false
